version: '3.1'

services:

  db:
    image: postgres:12.9-alpine
    networks:
      - db
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
  pgadmin:
    networks:
      - db
      - pgadmin
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
networks:
  db:
    driver: bridge

  pgadmin:
    driver: bridge
