# Generated by Django 4.1.2 on 2022-10-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=20, verbose_name='Album')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('width', models.IntegerField(verbose_name='Width')),
                ('height', models.IntegerField(verbose_name='Height')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('URL', models.URLField(verbose_name='URL')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.album')),
            ],
        ),
    ]
