# Generated by Django 4.1.1 on 2022-10-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photo_image_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='images/%Y/%m/%d/', width_field='width'),
        ),
    ]
