# Generated by Django 4.1.1 on 2022-10-28 00:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='URL',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='', verbose_name='URL'),
        ),
    ]
