# Generated by Django 4.1.1 on 2022-10-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Width'),
        ),
    ]
